import { StyleSheet, Platform, StatusBar } from 'react-native';
import { ThemeColors } from '../../constants/theme';

export const getStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    container: {
      flex: 1,
      paddingHorizontal: 16,
    },
    scrollContent: {
      paddingBottom: 110,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginVertical: 16,
    },
    greeting: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 2,
    },
    userName: {
      fontSize: 24,
      fontWeight: 'bold',
      color: colors.text,
    },
    profilePicPlaceholder: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.border,
    },
    balanceContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    label: {
      fontSize: 12,
      color: colors.textSecondary,
      marginBottom: 2,
    },
    balanceText: {
      fontSize: 34,
      fontWeight: 'bold',
      color: colors.text,
      marginRight: 8,
    },
    iconButton: {
      padding: 8,
    },
    subHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 16,
      marginBottom: 4,
    },
    subHeaderTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.text,
    },
    addAccountButton: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.surface,
      justifyContent: 'center',
      alignItems: 'center',
    },
    cashContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 16,
      marginVertical: 12,
    },
    cashLeftSection: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    cashIconBg: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.success,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    cashDetails: {
      justifyContent: 'center',
    },
    cashTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: 'bold',
    },
    cashSubtitle: {
      color: colors.textSecondary,
      fontSize: 12,
      marginTop: 2,
    },
    cashRightSection: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    cashAmount: {
      color: colors.text,
      fontSize: 16,
      fontWeight: 'bold',
      marginRight: 8,
    },
    sectionHeader: {
      marginTop: 8,
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.text,
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 20,
    },
    summaryCard: {
      width: '32%',
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 12,
      justifyContent: 'space-between',
      minHeight: 120,
    },
    summaryIconBg: {
      width: 28,
      height: 28,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'flex-start',
    },
    summaryCardLabel: {
      color: colors.textSecondary,
      fontSize: 11,
      marginTop: 8,
    },
    summaryCardValue: {
      color: colors.text,
      fontSize: 13,
      fontWeight: 'bold',
      marginVertical: 2,
    },
    summaryCardChange: {
      color: colors.textSecondary,
      fontSize: 9,
    },
    recentActivityHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 8,
      marginBottom: 12,
    },
    viewAllText: {
      color: colors.accent,
      fontSize: 13,
      fontWeight: '600',
    },
    transactionsContainer: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 8,
      marginBottom: 20,
    },
    transactionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
    },
    transactionLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    transactionIconBg: {
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    transactionTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: 'bold',
    },
    transactionSubtitle: {
      color: colors.textSecondary,
      fontSize: 11,
      marginTop: 2,
    },
    transactionRight: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    transactionAmount: {
      color: colors.text,
      fontSize: 14,
      fontWeight: 'bold',
    },
    cashAddText: {
      color: colors.accent,
      fontSize: 14,
      fontWeight: 'bold',
    },
    emptyTransactionsContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 32,
    },
    emptyTransactionsIconBg: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: colors.accentSubtle,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
    },
    emptyTransactionsTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: 'bold',
      marginBottom: 6,
    },
    emptyTransactionsSubtitle: {
      color: colors.textSecondary,
      fontSize: 12,
      textAlign: 'center',
      lineHeight: 18,
    },
    backdrop: {
      ...StyleSheet.absoluteFill,
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
      zIndex: 99,
    },
    fabContainer: {
      position: 'absolute',
      bottom: 24,
      right: 24,
      alignItems: 'flex-end',
      zIndex: 100,
    },
    fabButton: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.accent,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 8,
    },
    tooltipContainer: {
      position: 'absolute',
      bottom: 72,
      right: 0,
      backgroundColor: colors.surface,
      borderColor: colors.accent,
      borderWidth: 1.5,
      borderRadius: 16,
      paddingVertical: 8,
      width: 170,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 10,
      elevation: 10,
    },
    tooltipItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 16,
      gap: 12,
    },
    tooltipIconCircle: {
      width: 28,
      height: 28,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
    },
    tooltipText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
    },
    tooltipDivider: {
      height: 1,
      backgroundColor: colors.surfaceBorder,
      marginHorizontal: 16,
    },
    tooltipArrow: {
      position: 'absolute',
      bottom: -7,
      right: 22,
      width: 12,
      height: 12,
      backgroundColor: colors.surface,
      borderRightWidth: 1.5,
      borderBottomWidth: 1.5,
      borderColor: colors.accent,
      transform: [{ rotate: '45deg' }],
      zIndex: -1,
    },
  });
