import { StyleSheet, Platform, StatusBar } from 'react-native';
import { ThemeColors } from '../../constants/theme';

export const getStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    container: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 16,
      paddingBottom: 32,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginVertical: 16,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitleContainer: {
      flex: 1,
      marginLeft: 16,
    },
    headerSubtitle: {
      fontSize: 12,
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      color: colors.text,
      marginTop: 2,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    cardPreviewContainer: {
      width: '100%',
      height: 190,
      borderRadius: 24,
      overflow: 'hidden',
      marginTop: 16,
      marginBottom: 24,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.3,
      shadowRadius: 14,
      elevation: 8,
    },
    cardPreviewGradient: {
      flex: 1,
      padding: 24,
      justifyContent: 'space-between',
    },
    cardPreviewHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    cardPreviewBottom: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'flex-end',
    },
    cardChip: {
      width: 44,
      height: 32,
      borderRadius: 6,
      backgroundColor: '#E5E5EA',
      borderWidth: 1,
      borderColor: 'rgba(0, 0, 0, 0.15)',
      padding: 4,
      justifyContent: 'space-between',
    },
    chipInnerLineRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      flex: 1,
    },
    chipInnerLineLeft: {
      width: 10,
      borderRightWidth: 1.5,
      borderBottomWidth: 1.5,
      borderColor: 'rgba(0, 0, 0, 0.2)',
    },
    chipInnerLineRight: {
      width: 10,
      borderLeftWidth: 1.5,
      borderBottomWidth: 1.5,
      borderColor: 'rgba(0, 0, 0, 0.2)',
    },
    chipMiddleDivider: {
      height: 1.5,
      backgroundColor: 'rgba(0, 0, 0, 0.2)',
      marginVertical: 1,
    },
    chipInnerLineLeftBottom: {
      width: 10,
      borderRightWidth: 1.5,
      borderTopWidth: 1.5,
      borderColor: 'rgba(0, 0, 0, 0.2)',
    },
    chipInnerLineRightBottom: {
      width: 10,
      borderLeftWidth: 1.5,
      borderTopWidth: 1.5,
      borderColor: 'rgba(0, 0, 0, 0.2)',
    },
    form: {
      marginTop: 16,
      gap: 16,
    },
    formGroup: {
      gap: 8,
    },
    label: {
      fontSize: 13,
      color: colors.textSecondary,
      fontWeight: '500',
    },
    input: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 14,
      paddingHorizontal: 16,
      height: 52,
      color: colors.text,
      fontSize: 14,
    },
    dropdownContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 14,
      paddingHorizontal: 16,
      height: 52,
    },
    dropdownText: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    dropdownTextActive: {
      color: colors.text,
    },
    cardTypesRow: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 4,
    },
    cardTypeButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 60,
    },
    cardTypeButtonSelected: {
      borderColor: colors.accent,
      backgroundColor: colors.accentSubtle,
    },
    cardTypeButtonText: {
      fontSize: 12,
      fontWeight: 'bold',
      color: colors.textSecondary,
    },
    cardTypeButtonTextSelected: {
      color: colors.text,
    },
    amountInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 14,
      paddingHorizontal: 12,
      height: 52,
    },
    amountIconCircle: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.accentSubtle,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 10,
    },
    amountInput: {
      flex: 1,
      color: colors.text,
      fontSize: 15,
      padding: 0,
    },
    amountCurrencyText: {
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: 'bold',
      marginLeft: 10,
    },
    colorsRow: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'center',
      paddingVertical: 4,
    },
    colorCircle: {
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
    },
    colorCircleSelected: {},
    colorCheck: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#FFFFFF',
    },
    notesContainer: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 14,
      padding: 12,
      height: 100,
      justifyContent: 'space-between',
    },
    notesInput: {
      color: colors.text,
      fontSize: 14,
      height: 64,
      textAlignVertical: 'top',
      padding: 0,
    },
    charCounter: {
      fontSize: 10,
      color: colors.textSecondary,
      alignSelf: 'flex-end',
    },
    submitButton: {
      marginTop: 32,
      borderRadius: 24,
      height: 52,
      overflow: 'hidden',
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 6,
    },
    submitButtonGradient: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    submitButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
    sheetContent: {
      paddingHorizontal: 16,
      paddingTop: 8,
    },
    sheetTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: colors.text,
      marginBottom: 20,
    },
    sheetItemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 14,
      marginBottom: 10,
    },
    sheetItemLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    sheetItemText: {
      fontSize: 15,
      fontWeight: 'bold',
      color: colors.text,
    },
    sheetGenericIconContainer: {
      width: 45,
      height: 30,
      backgroundColor: colors.background,
      borderRadius: 6,
      justifyContent: 'center',
      alignItems: 'center',
    },
  });
