import { StyleSheet, Platform, StatusBar } from 'react-native';
import { theme } from '../../constants/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#090A0C', // Deep premium dark background
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: theme.spacing.m,
    paddingBottom: theme.spacing.xl,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: theme.spacing.m,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#1E1F25',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitleContainer: {
    flex: 1,
    marginLeft: theme.spacing.m,
  },
  headerSubtitle: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.4)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 2,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: theme.spacing.l,
    marginBottom: theme.spacing.m,
  },
  accountTypeRow: {
    flexDirection: 'row',
    gap: 12,
  },
  accountTypeCard: {
    flex: 1,
    backgroundColor: '#131418',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#1E1F25',
    height: 140,
    justifyContent: 'space-between',
  },
  accountTypeCardSelected: {
    borderColor: '#7F56D9',
    backgroundColor: '#1B1826',
    // Subtle glow on selected card type
    shadowColor: '#7F56D9',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  accountTypeIconContainer: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#1E1F25',
    justifyContent: 'center',
    alignItems: 'center',
  },
  accountTypeIconContainerSelected: {
    backgroundColor: '#2D224D',
  },
  accountTypeTextContainer: {
    marginTop: 8,
  },
  accountTypeTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  accountTypeDesc: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.4)',
    marginTop: 4,
    lineHeight: 14,
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioOuterSelected: {
    borderColor: '#FFFFFF',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
  },
  form: {
    marginTop: theme.spacing.m,
    gap: 16,
  },
  formGroup: {
    gap: 8,
  },
  label: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.6)',
    fontWeight: '500',
  },
  input: {
    backgroundColor: '#131418',
    borderColor: '#1E1F25',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 16,
    height: 52,
    color: '#FFFFFF',
    fontSize: 14,
  },
  dropdownContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#131418',
    borderColor: '#1E1F25',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 16,
    height: 52,
  },
  dropdownText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.4)',
  },
  dropdownTextActive: {
    color: '#FFFFFF',
  },
  cardTypesRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  cardTypeButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#131418',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1E1F25',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 60,
  },
  cardTypeButtonSelected: {
    borderColor: '#7F56D9',
    backgroundColor: '#2D224D',
  },
  cardTypeButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'rgba(255, 255, 255, 0.6)',
  },
  cardTypeButtonTextSelected: {
    color: '#FFFFFF',
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#131418',
    borderColor: '#1E1F25',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    height: 52,
  },
  amountIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  amountInput: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 15,
    padding: 0,
  },
  amountCurrencyText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.4)',
    fontWeight: 'bold',
    marginLeft: 10,
  },
  colorsRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    paddingVertical: 4,
  },
  colorCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  colorCircleSelected: {
    borderWidth: 2,
    borderColor: '#FFFFFF',
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  colorCheck: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
  },
  notesContainer: {
    backgroundColor: '#131418',
    borderColor: '#1E1F25',
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
    height: 100,
    justifyContent: 'space-between',
  },
  notesInput: {
    color: '#FFFFFF',
    fontSize: 14,
    height: 64,
    textAlignVertical: 'top',
    padding: 0,
  },
  charCounter: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.3)',
    alignSelf: 'flex-end',
  },
  submitButton: {
    marginTop: theme.spacing.xl,
    borderRadius: 24,
    height: 52,
    overflow: 'hidden',
    shadowColor: '#7F56D9',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  submitButtonGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  sheetContent: {
    paddingHorizontal: theme.spacing.m,
    paddingTop: 8,
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 20,
  },
  sheetItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#131418',
    borderWidth: 1,
    borderColor: '#1E1F25',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 10,
  },
  sheetItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  sheetItemText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  sheetGenericIconContainer: {
    width: 45,
    height: 30,
    backgroundColor: '#1E1F25',
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
