import { StyleSheet, Platform, StatusBar } from 'react-native';
import { ThemeColors } from '../../constants/theme';

export const getStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    container: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 16,
      paddingBottom: 32,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginVertical: 16,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitleContainer: {
      flex: 1,
      marginLeft: 16,
    },
    headerSubtitle: {
      fontSize: 12,
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      color: colors.text,
      marginTop: 2,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    cardPreviewContainer: {
      width: '100%',
      height: 190,
      borderRadius: 24,
      overflow: 'hidden',
      marginTop: 16,
      marginBottom: 24,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.3,
      shadowRadius: 14,
      elevation: 8,
    },
    cardPreviewGradient: {
      flex: 1,
      padding: 24,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      position: 'relative',
    },
    cardPreviewLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      flex: 1,
      zIndex: 2,
    },
    banknoteIconContainer: {
      width: 48,
      height: 48,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
    },
    cardPreviewTextContainer: {
      flex: 1,
    },
    cardPreviewTitle: {
      color: '#FFFFFF',
      fontSize: 22,
      fontWeight: 'bold',
    },
    cardPreviewSubtitle: {
      color: 'rgba(255, 255, 255, 0.7)',
      fontSize: 13,
      marginTop: 4,
      lineHeight: 18,
    },
    banknoteIllustration: {
      position: 'absolute',
      right: -15,
      bottom: -10,
      opacity: 0.08,
      transform: [{ rotate: '-15deg' }, { scale: 1.2 }],
      zIndex: 1,
    },
    form: {
      marginTop: 16,
      gap: 20,
    },
    formGroup: {
      gap: 8,
    },
    label: {
      fontSize: 13,
      color: colors.textSecondary,
      fontWeight: '500',
    },
    input: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 14,
      paddingHorizontal: 16,
      height: 52,
      color: colors.text,
      fontSize: 14,
    },
    amountInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 14,
      paddingHorizontal: 12,
      height: 52,
    },
    amountIconCircle: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.accentSubtle,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 10,
    },
    amountInput: {
      flex: 1,
      color: colors.text,
      fontSize: 15,
      padding: 0,
    },
    amountCurrencyText: {
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: 'bold',
      marginLeft: 10,
    },
    colorsRow: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'center',
      paddingVertical: 4,
    },
    colorCircle: {
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
    },
    colorCheck: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#FFFFFF',
    },
    submitButton: {
      marginTop: 16,
      borderRadius: 24,
      height: 52,
      overflow: 'hidden',
      elevation: 4,
    },
    submitButtonGradient: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    submitButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
  });
