import { StyleSheet, Platform, StatusBar } from 'react-native';
import { ThemeColors } from '../../constants/theme';

export const getStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    container: {
      flex: 1,
      paddingHorizontal: 16,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
      marginBottom: 16,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      flex: 1,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surface,
      justifyContent: 'center',
      alignItems: 'center',
    },
    titleContainer: {
      justifyContent: 'center',
    },
    subtitle: {
      fontSize: 12,
      color: colors.textSecondary,
      marginBottom: 2,
    },
    title: {
      fontSize: 22,
      fontWeight: 'bold',
      color: colors.text,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    searchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 16,
    },
    searchContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 16,
      height: 52,
      paddingHorizontal: 16,
      gap: 10,
    },
    searchIcon: {
      marginRight: 2,
    },
    searchInput: {
      flex: 1,
      color: colors.text,
      fontSize: 15,
      paddingVertical: 8,
    },
    addButtonGradient: {
      width: 52,
      height: 52,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
    },
    addButton: {
      width: 52,
      height: 52,
      borderRadius: 16,
      overflow: 'hidden',
    },
    sectionHeader: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      marginTop: 8,
      marginBottom: 16,
    },
    popularGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      justifyContent: 'space-between',
      marginBottom: 24,
    },
    popularCard: {
      width: '23%',
      height: 86,
      backgroundColor: colors.surface,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 6,
    },
    popularText: {
      fontSize: 10,
      color: colors.text,
      textAlign: 'center',
      marginTop: 8,
      fontWeight: '500',
    },
    listContainer: {
      paddingBottom: 40,
    },
    categoryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 14,
      marginBottom: 8,
    },
    categoryLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    iconBadge: {
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
    },
    categoryText: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '500',
    },
    chevron: {
      opacity: 0.5,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      justifyContent: 'flex-end',
    },
    modalContainer: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 16,
      paddingTop: 24,
      paddingBottom: Platform.OS === 'ios' ? 40 : 24,
      borderWidth: 1,
      borderColor: colors.surfaceBorder,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 24,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: colors.text,
    },
    modalCloseButton: {
      padding: 4,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textSecondary,
      marginBottom: 8,
      marginTop: 8,
    },
    modalInput: {
      backgroundColor: colors.background,
      borderRadius: 16,
      height: 52,
      color: colors.text,
      paddingHorizontal: 16,
      fontSize: 16,
      marginBottom: 16,
    },
    selectorScroll: {
      marginBottom: 16,
    },
    colorBubble: {
      width: 44,
      height: 44,
      borderRadius: 22,
      marginRight: 12,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: 'transparent',
    },
    colorBubbleSelected: {
      borderColor: colors.text,
    },
    iconBubble: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.background,
      marginRight: 12,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: 'transparent',
    },
    iconBubbleSelected: {
      borderColor: colors.accent,
      backgroundColor: colors.accentSubtle,
    },
    submitButton: {
      borderRadius: 16,
      height: 52,
      overflow: 'hidden',
      marginTop: 16,
    },
    submitButtonGradient: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    submitButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
  });
